### PR TITLE
[WIP] Use .env for bearerToken in build.gradle.kts

### PR DESCRIPTION
**Pull request by HerXayah**
As above, this is WIP.
The in its state it will and does work, the problem however is, that Loading Script Configurations or Gradle Changes will fail due to the env beeing Unresolved.
If its possible to skip it, implement it, ive been trying for 2 hours now.

### CODE REVIEW

**Comment by l3nnartt** [comment]
I dont get the point of this? What speaks against the use of gradle.properties?

**Comment by jumpingpxl** [comment]
Hey, 
I will close this pull request for two reasons:
1. **This is the addon template for LabyMod 4. Due to LabyMod 4 being in closed beta, access to the addon API is restricted to beta testers.** 
2. The way to go would be to declare the authentication in the global gradle.properties file. We don't recommend using any other file, especially not if an extra plugin is needed. 

If you do already have beta access, send me a dm on Discord (JumpingPxl#2395).

**Comment by HerXayah** [comment]
> I dont get the point of this? What speaks against the use of gradle.properties?

0 documentation.
How am i supposed to know any of this when its written nowhere.

**Comment by l3nnartt** [comment]
This is not true, on the labymod discord it says ["Anyone interested in creating addons for LabyMod 4 can send me dm"](https://discord.com/channels/260471731809026048/1043268839170916352/1043282549931266128)
I saw that you are also on the dev discord too, there it is also [explicitly mentioned](https://discord.com/channels/412724944112320513/1052932816062656512/1052938158800642108) multiple times.

If you then have beta access, you get access to a beta category (wiki channel and channel where you can ask for help) where it is explained in detail how to develop an addon during the beta phase & how to use the token.

**Comment by HerXayah** [comment]
> This is not true, on the labymod discord it says ["Anyone interested in creating addons for LabyMod 4 can send me dm"](https://discord.com/channels/260471731809026048/1043268839170916352/1043282549931266128) I saw that you are also on the dev discord too, there it is also [explicitly mentioned](https://discord.com/channels/412724944112320513/1052932816062656512/1052938158800642108) multiple times.
> 
> If you then have beta access, you get access to a beta category (wiki channel and channel where you can ask for help) where it is explained in detail how to develop an addon during the beta phase & how to use the token.

i do have beta access.
wasnt my point.
its hard for ppl not on there to get started because they first need to join somewhere etc etc.
if the wiki just mentioned if you have token to put it into the global file im okay.
that is my point.

**Pull request closed without merging**
